getwd()
setwd("C:/Users/ankit/Desktop/") 
getwd()
x <- read.csv("GS16.csv",header = FALSE, sep = ",")
#x <- read.csv("threshold_200_34.7.csv",header = FALSE, sep = ",")
df <- as.data.frame(t(x))
class(df)
xframe = data.frame(df)
z <- as.numeric(unlist(df))
class(z)
is.numeric(z)
t <- t(z)
#t1 <- t * 1000
extremogram1(t, 0.99, 100, 1, ploting = 1, cutoff = 1, start = 0)
